// <auto-generated />
using System;
using AlemarBudgetelHotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlemarBudgetelHotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214161856_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.HousekeepingTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedToAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedToAdminId");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("RoomId");

                    b.ToTable("HousekeepingTasks");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GCashPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GCashReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentProof")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime?>("ActualCheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckedInByAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("CheckedOutByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price12Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price24Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price3Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2362),
                            Description = "Cozy single room",
                            Floor = 1,
                            ImageUrl = "/images/rooms/single.jpg",
                            Price12Hours = 800m,
                            Price24Hours = 1200m,
                            Price3Hours = 300m,
                            RoomNumber = "101",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            RoomId = 2,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2372),
                            Description = "Cozy single room",
                            Floor = 1,
                            ImageUrl = "/images/rooms/single.jpg",
                            Price12Hours = 800m,
                            Price24Hours = 1200m,
                            Price3Hours = 300m,
                            RoomNumber = "102",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            RoomId = 3,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2383),
                            Description = "Cozy single room",
                            Floor = 1,
                            ImageUrl = "/images/rooms/single.jpg",
                            Price12Hours = 800m,
                            Price24Hours = 1200m,
                            Price3Hours = 300m,
                            RoomNumber = "103",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            RoomId = 4,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2393),
                            Description = "Comfortable double room",
                            Floor = 2,
                            ImageUrl = "/images/rooms/double.jpg",
                            Price12Hours = 1200m,
                            Price24Hours = 1800m,
                            Price3Hours = 500m,
                            RoomNumber = "201",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            RoomId = 5,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2403),
                            Description = "Comfortable double room",
                            Floor = 2,
                            ImageUrl = "/images/rooms/double.jpg",
                            Price12Hours = 1200m,
                            Price24Hours = 1800m,
                            Price3Hours = 500m,
                            RoomNumber = "202",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            RoomId = 6,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2411),
                            Description = "Comfortable double room",
                            Floor = 2,
                            ImageUrl = "/images/rooms/double.jpg",
                            Price12Hours = 1200m,
                            Price24Hours = 1800m,
                            Price3Hours = 500m,
                            RoomNumber = "203",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            RoomId = 7,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2420),
                            Description = "Standard room with modern amenities",
                            Floor = 3,
                            ImageUrl = "/images/rooms/standard.jpg",
                            Price12Hours = 1800m,
                            Price24Hours = 2500m,
                            Price3Hours = 700m,
                            RoomNumber = "301",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            RoomId = 8,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2428),
                            Description = "Standard room with modern amenities",
                            Floor = 3,
                            ImageUrl = "/images/rooms/standard.jpg",
                            Price12Hours = 1800m,
                            Price24Hours = 2500m,
                            Price3Hours = 700m,
                            RoomNumber = "302",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            RoomId = 9,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2436),
                            Description = "Standard room with modern amenities",
                            Floor = 3,
                            ImageUrl = "/images/rooms/standard.jpg",
                            Price12Hours = 1800m,
                            Price24Hours = 2500m,
                            Price3Hours = 700m,
                            RoomNumber = "303",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            RoomId = 10,
                            Capacity = 3,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2443),
                            Description = "Deluxe room with premium facilities",
                            Floor = 4,
                            ImageUrl = "/images/rooms/deluxe.jpg",
                            Price12Hours = 2500m,
                            Price24Hours = 3500m,
                            Price3Hours = 1000m,
                            RoomNumber = "401",
                            Status = 0,
                            Type = 3
                        },
                        new
                        {
                            RoomId = 11,
                            Capacity = 3,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2451),
                            Description = "Deluxe room with premium facilities",
                            Floor = 4,
                            ImageUrl = "/images/rooms/deluxe.jpg",
                            Price12Hours = 2500m,
                            Price24Hours = 3500m,
                            Price3Hours = 1000m,
                            RoomNumber = "402",
                            Status = 0,
                            Type = 3
                        },
                        new
                        {
                            RoomId = 12,
                            Capacity = 3,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2459),
                            Description = "Deluxe room with premium facilities",
                            Floor = 4,
                            ImageUrl = "/images/rooms/deluxe.jpg",
                            Price12Hours = 2500m,
                            Price24Hours = 3500m,
                            Price3Hours = 1000m,
                            RoomNumber = "403",
                            Status = 0,
                            Type = 3
                        },
                        new
                        {
                            RoomId = 13,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2467),
                            Description = "Super deluxe room with luxury amenities",
                            Floor = 5,
                            ImageUrl = "/images/rooms/super-deluxe.jpg",
                            Price12Hours = 3500m,
                            Price24Hours = 5000m,
                            Price3Hours = 1500m,
                            RoomNumber = "501",
                            Status = 0,
                            Type = 4
                        },
                        new
                        {
                            RoomId = 14,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2476),
                            Description = "Super deluxe room with luxury amenities",
                            Floor = 5,
                            ImageUrl = "/images/rooms/super-deluxe.jpg",
                            Price12Hours = 3500m,
                            Price24Hours = 5000m,
                            Price3Hours = 1500m,
                            RoomNumber = "502",
                            Status = 0,
                            Type = 4
                        },
                        new
                        {
                            RoomId = 15,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2484),
                            Description = "Super deluxe room with luxury amenities",
                            Floor = 5,
                            ImageUrl = "/images/rooms/super-deluxe.jpg",
                            Price12Hours = 3500m,
                            Price24Hours = 5000m,
                            Price3Hours = 1500m,
                            RoomNumber = "503",
                            Status = 0,
                            Type = 4
                        },
                        new
                        {
                            RoomId = 16,
                            Capacity = 5,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2492),
                            Description = "Premium super duper suite",
                            Floor = 6,
                            ImageUrl = "/images/rooms/super-duper.jpg",
                            Price12Hours = 5000m,
                            Price24Hours = 7000m,
                            Price3Hours = 2000m,
                            RoomNumber = "601",
                            Status = 0,
                            Type = 5
                        },
                        new
                        {
                            RoomId = 17,
                            Capacity = 5,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2500),
                            Description = "Premium super duper suite",
                            Floor = 6,
                            ImageUrl = "/images/rooms/super-duper.jpg",
                            Price12Hours = 5000m,
                            Price24Hours = 7000m,
                            Price3Hours = 2000m,
                            RoomNumber = "602",
                            Status = 0,
                            Type = 5
                        },
                        new
                        {
                            RoomId = 18,
                            Capacity = 5,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 18, 53, 782, DateTimeKind.Local).AddTicks(2507),
                            Description = "Premium super duper suite",
                            Floor = 6,
                            ImageUrl = "/images/rooms/super-duper.jpg",
                            Price12Hours = 5000m,
                            Price24Hours = 7000m,
                            Price3Hours = 2000m,
                            RoomNumber = "603",
                            Status = 0,
                            Type = 5
                        });
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.HousekeepingTask", b =>
                {
                    b.HasOne("AlemarBudgetelHotel.Models.Admin", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlemarBudgetelHotel.Models.Admin", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlemarBudgetelHotel.Models.Room", "Room")
                        .WithMany("HousekeepingTasks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Payment", b =>
                {
                    b.HasOne("AlemarBudgetelHotel.Models.Reservation", "Reservation")
                        .WithOne("Payment")
                        .HasForeignKey("AlemarBudgetelHotel.Models.Payment", "ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Reservation", b =>
                {
                    b.HasOne("AlemarBudgetelHotel.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlemarBudgetelHotel.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Reservation", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("AlemarBudgetelHotel.Models.Room", b =>
                {
                    b.Navigation("HousekeepingTasks");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
